repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      -  id: mypy
         args:
         -   --disallow-incomplete-defs
         -   --ignore-missing-imports
         -   --no-warn-no-return
         -   --disable-error-code
         -   attr-defined
-   repo: https://github.com/hakancelikdev/unimport
    rev: 0.9.6
    hooks:
      - id: unimport
        args:
        -   --remove
        -   --ignore-init
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
